### ISSUE TITLE
AUR & Nix Packages

### ISSUE THREAD

**Issue by CarwynNelson** [jonhoo/yambar-hyprland-wses#1]
Hi Jon,

First off I want to thank you for creating this utility, it has made Hyprland usable for me :)

I was building the package locally in order to get the fixes for Hyprland 0.40 and figured I may as well create a package on the AUR. The link to the package is https://aur.archlinux.org/packages/yambar-hyprland-wses.

I also noticed in my searching that someone has created a nix package although this is using v0.1.0 (https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/misc/yambar-hyprland-wses/default.nix)

I am creating this issue to see if you are interested in a pull request to add these packages to the documentation.

**Comment by jonhoo** [comment]
Hey! Oh, nice — yeah, I'd be happy to have those listed in the README :+1:

**Comment by CarwynNelson** [comment]
Awesome :)

I have raised https://github.com/jonhoo/yambar-hyprland-wses/pull/2 to add these to the documentation.
